import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import DataProvider, { useData } from "@/context/DataProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "App Store",
  description: "Generated by app store",
};

export default function RootLayout({ children }) {
  const { data, loading } = useData;
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="min-h-screen flex flex-col">
        <NavBar />
        <DataProvider>
          <main className="container mx-auto px-4">{children}</main>
        </DataProvider>
      </body>
    </html>
  );
}
